matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script: cd ServerCode/java8
    - language: csharp
      mono: none
      dotnet: 2.0.0
      before_script: cd ServerCode/csharp
      script:
        - dotnet restore
        - dotnet build
